---
- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  become: true

- name: Reiniciar php
  ansible.builtin.service:
    name: "{{ php_fpm_service }}"
    state: restarted
  become: true
