---
# Playbook de convergencia para Docker
# Ejecuta nuestro rol nginx_wordpress

- name: Converge
  hosts: all
  become: true
  roles:
    - role: .
  vars:
    mysql_databases:
      - name: wordpress
        encoding: utf8mb4
        collation: utf8mb4_general_ci

    mysql_users:
      - name: wpuser
        host: localhost
        password: secret123
        priv: "wordpress.*:ALL"
