---
# Playbook de preparación para Docker
# Instala dependencias necesarias antes de ejecutar el rol

- name: Prepare
  hosts: all
  become: true
  tasks:
    # Actualizar caché de paquetes en Debian/Ubuntu
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == "Debian"

    # Actualizar caché de paquetes en RedHat/Rocky
    - name: Update dnf cache
      ansible.builtin.dnf:
        update_cache: true
      when: ansible_os_family == "RedHat"

    # Instalar Python3 (necesario para Ansible)
    - name: Install Python3
      ansible.builtin.package:
        name: python3
        state: present

    # Instalar certificados SSL (necesario para descargas HTTPS)
    - name: Install CA certificates
      ansible.builtin.package:
        name: ca-certificates
        state: present
