name: CI + Publish to Galaxy

on:
  push:
    tags:
      - 'v*.*.*'  # Solo publica si hacés push de un tag semántico

jobs:
  test:
    name: Molecule Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible "molecule<25.0" molecule-docker ansible-lint

      - name: Install Galaxy dependencies
        run: |
          ansible-galaxy install -r molecule/default/requirements.yml

      - name: Run Molecule tests
        run: molecule test

  publish:
    name: Publish to Ansible Galaxy
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible

      - name: Publish role to Galaxy
        env:
          ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        run: >
          ansible-galaxy role import
          --api-key $ANSIBLE_GALAXY_TOKEN
          cibarraleonel role-nginx-wordpress
