name: Molecule CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible "molecule<25.0" molecule-docker ansible-lint

      - name: Install Ansible Galaxy roles
        run: |
          ansible-galaxy install -r molecule/default/requirements.yml

      - name: Run Molecule tests
        run: molecule test
